####################################################
#     /  |/  /___ _/ /_____  / __(_) /__ 
#    / /|_/ / __ `/ //_/ _ \/ /_/ / / _ \
#   / /  / / /_/ / ,< /  __/ __/ / /  __/
#  /_/  /_/\__,_/_/|_|\___/_/ /_/_/\___/ 
#
#
# This Makefile is for testing Super-Deduper
# in all of it's default settings.
# We are using an outside python script 
# 
#
# The Makefile caveat is that you have
# to use tabs and not spaces.
.PHONY: clean default install build distclean debug
pyScript=testFlash.py
test:
	python $(pyScript) 

